#!/bin/bash
# @echo off statement not needed in bash
# Instead, we use what is on line one?

# Functions come first. Param check is at the bottom

Help ()
{ 
  if [ -e HelpDoc.txt ]
    then
      cat HelpDoc.txt
      exit
    else
      echo The help documentary does not appear to be installed.
	echo Error: HelpDoc.txt is missing
	echo You can view and download the help docs from Github at https://www.gitub.com/jordanbancino/apk-manager
        xdg-open https://github.com/jordanbancino/apk-manager/blob/master/Windows/HelpDoc.txt
  fi
} 


# Verify The Parameters
if [ $# -eq 0 ];then echo "Missing Arguments." && echo "For help, use $0 help" && exit; fi
if [ "$1" = "verify" ];then Verify; fi
if [ "$1" = "decompile" ];then Verify; fi
if [ "$1" = "compile" ];then Verify; fi
if [ "$1" = "help" ];then Help; fi
if [ "$1" = "about" ];then About; fi
if [ "$1" = "install" ];then Install; fi
if [ "$1" = "devices" ];then ChkCon; fi
if [ "$1" = "sign" ];then Sign; fi
echo "That is not valid input"
echo "For help, use $0 help"
exit



