#!/bin/bash
# @echo off statement not needed in bash
# Instead, we use what is on line one?

# Functions come first. Param check is at the bottom

_help ()
{ 
  if [ -e HelpDoc.txt ]
    then
      cat HelpDoc.txt
      exit
    else
      echo The help documentary does not appear to be installed.
	echo Error: HelpDoc.txt is missing
	echo You can view and download the help docs from Github at https://www.gitub.com/jordanbancino/apk-manager
        xdg-open https://github.com/jordanbancino/apk-manager/blob/master/Windows/HelpDoc.txt
  fi
} 


# Verify The Parameters

if [ $# -eq 0 ]
  then
    echo "Missing parameters."
    echo "For help, use $0 help"
    exit
fi
if [ "$1" = "verify" ]
  then
    echo "You typed 'verify' "
    echo "This is where we would go to the Verify block"
    exit.
fi
if [ "$1" = "decompile" ]
  then
    echo "You typed 'decompile' "
    echo "This is where we would still go to the Verify block"
    exit
fi
if [ "$1" = "compile" ]
  then
    echo "You typed 'verify' "
    echo "This is where we would go to the Verify block, yet again"
    exit
fi
if [ "$1" = "help" ]
  then
    # Help
    _help
    exit
fi
# Parameters were entered, but are not valid
echo Invalid Parameter.
echo Use "./apk-manager help" for availible options
# No more to do, exit
exit



